### ISSUE TITLE
部分npm在贵司私有服务器？无法下载

### ISSUE THREAD

**Issue by AlexZhong22c** [aliyun/cloud-design#2]
复现：拉取项目，并`npm run boot`，结果报错：

```
error An unexpected error occurred: "https://registry.npm.alibaba-inc.com/@rollup/pluginutils/download/@rollup/pluginutils-3.1.0.tgz: ETIMEDOUT"
```

发现该npm源不是来自https://registry.npm.taobao.org，而是来自https://registry.npm.alibaba-inc.com

**Comment by zuoqi705** [comment]
fixed

**Comment by AlexZhong22c** [comment]
> fixed https://github.com/aliyun/cloud-design/commit/58482b73a3fd9c7075ff101f20e33616b126d864

@zuoqi705  直接从github拉下来，还是同样的报错

**Comment by zuoqi705** [comment]
![image](https://user-images.githubusercontent.com/30346283/100959452-3dcae280-3559-11eb-94c2-25871b46de27.png)
哦，把这个注释掉换成 taobao 的呢

**Comment by heyDolby** [comment]
> ![image](https://user-images.githubusercontent.com/30346283/100959452-3dcae280-3559-11eb-94c2-25871b46de27.png)
> 哦，把这个注释掉换成 taobao 的呢

还是不行呢
